### PR TITLE
Move to webjars

### PR DESCRIPTION
**Pull request by jamesward**

### CODE REVIEW

**Comment by olada** [comment]
Hi @jamesward ,

now I am the cuplrit.... sorry for the delay.
Looks good to me.

Personally, I would prefer, if the artifact name would be "webjars-webfilter-resolver" - the only reason being to reduce the chance of artifact name clashes, since "webfilter-resolver" sounds somewhat generic.

However, if you feel that the chance is low enough - we can leave it at "webfilter-resolver".

Cheers
David

**Comment by jamesward** [comment]
Since it has the `org.webjars` groupId we should be good.

**Comment by jamesward** [comment]
Oh, but it looks like our convention is to prefix with `webjars-` so I'll switch that back.

**Comment by jamesward** [comment]
I've released `0.1.1` to Maven Central.  Thanks for your help!

**Comment by olada** [comment]
Perfect - and it makes perfect sense since the group id is not part of the artifact name (talking about the actual name of the jar).
Well done, no problem!

**Pull request merged**
